### ISSUE TITLE
program not running for 1/3 members 

### ISSUE THREAD

**Issue by aguerradelgado** [aguerradelgado/goodreads_webscraper_2#24]
![image](https://user-images.githubusercontent.com/62119621/205511827-fe4e9f04-239c-4faa-974c-4da8a3bf4f5c.png)

**Comment by aguerradelgado** [comment]
has been working before for, but since latest changes, error appearing. Exception on /result

**Comment by aguerradelgado** [comment]
when i run again I get the same error but different values in the result, this one just description and tbr, previous listed rating, books_give, titiles_give 

![image](https://user-images.githubusercontent.com/62119621/205512185-583b4f6e-f313-42f2-a0ca-460bb042f37d.png)

have tried five books never previously searched, only this error comes up now

**Comment by aguerradelgado** [comment]
this issue was resolved by adding in session["tbr} = [] in def login. There was nothing being passed to the render previously while in GET so error

**Comment by patriciaandreica** [comment]
<img width="846" alt="Screen Shot 2022-12-04 at 3 47 26 PM" src="https://user-images.githubusercontent.com/68759170/205514790-8acf02c8-2b11-4729-83f0-36213f601f18.png">

I get this error which no one else is getting. Making them as globals solves the problem (though that is bad practice),but  I am also just confused why no one else gets that error. Could be the requests not going through on my part?

**Comment by jsgreenwell** [comment]
> Making them as globals solves the problem

This is because you need to pass the variable that is being reference to the function over using a global. Same as C++ and Java when you need a variable's value you pass it as a reference to the function for use/updating.

At a guess, your getting this error because you didn't update/fetch the code so your slightly out of date or because of cacheing (as browsers' heavily cache all content for performance).
