### ISSUE TITLE
download csv script no longer working 

### ISSUE THREAD

**Issue by aguerradelgado** [aguerradelgado/goodreads_webscraper_2#25]
![image](https://user-images.githubusercontent.com/62119621/205514665-7223f07b-d9bf-4d6a-b2a8-690b15610fac.png)

script above is only getting the first book added to the tbr cart, despite the tbr cart having several. print in python showing all added books. was working before, cant identify what might have changed

**Comment by jsgreenwell** [comment]
your using |safe which tells jinja to safe (filter) results and add html tags raw (so bold becomes `<b>bold</b>`). This means it is taking it as a string not a list. If you are passing a list use `{{ tbr | tojson }}` as using [tojson](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.tojson) sets up both safe rendering and processes a list as a list (in this case changes a Python list to a JavaScript JSON list). 

Secondary note, didn't get to go into MVC and other ways of building this due to time, you should have a secondary python script called view.py which handles rendering views then just import and call it in app.py as there are a lot of overlapping changes in your commits (simply because all the code is in one place) which would cause more problems down the road.

**Comment by aguerradelgado** [comment]
thank you, I changed that, and am still having the same issue. It is strange because the list is being appended too correctly, 
Here is the tbr cart:
![image](https://user-images.githubusercontent.com/62119621/205524001-29869d37-0e17-49e0-a181-c2f2ca232c76.png)

here it is printed in console 
![image](https://user-images.githubusercontent.com/62119621/205524039-1fd2d2a2-1397-4800-922f-76a255d4bd22.png)

here is what shows when download csv
![image](https://user-images.githubusercontent.com/62119621/205524087-4b1f5b71-7fc1-4d9e-899b-cd2b21092d72.png)

and here is the changed code
![image](https://user-images.githubusercontent.com/62119621/205524062-119565b0-1674-44f6-a3e7-aeda24ded1c5.png)


I am having a hard time wrapping my head around this because it is working for grace right now with tbr | safe, and it had worked with that before, but not anymore.
